[package]
name = "core"
edition.workspace = true
publish.workspace = true

[dependencies]
tokio.workspace = true
anyhow.workspace = true
rig-core.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
